### ISSUE TITLE
duplicate class

### ISSUE THREAD

**Issue by WeiHungHuang** [adaptech-cz/Tesseract4Android#39]
The following error shows when building app 
  java.lang.RuntimeException: Duplicate class com.googlecode.leptonica.android.AdaptiveMap found in modules tesseract4android-4.1.0-runtime.jar (cz.adaptech.tesseract4android:tesseract4android:4.1.0) and tesseract4android-openmp-4.1.0-runtime.jar (cz.adaptech.tesseract4android:tesseract4android-openmp:4.1.0)

Here is the build.gradle
`dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation project(path: ':opencv')
    implementation ('cz.adaptech:tesseract4android:4.1.0')
//    implementation 'cz.adaptech:tesseract4android-openmp:4.1.0'

}
`

**Comment by Robyer** [comment]
OpenCV doesn't contain Leptonica when you download official package from https://opencv.org
That means you probably downloaded some user-made library which combined OpenCV AND Leptonica, same as Tesseract4Android combines Tesseract + Leptonica.

So use official OpenCV package. Otherwise you need to create your own build where you will combine Tesseract, Leptonica and OpenCV.

**Comment by WeiHungHuang** [comment]
It's not related with OpenCV.

Only cz.adaptech:tesseract4android:4.1.0 is included in build.gradle from jitpack.io
        maven { url 'https://jitpack.io' }

implementation ('cz.adaptech:tesseract4android:4.1.0')

However, the error showed that tesseract4android-openmp was also included as shown below

java.lang.RuntimeException: Duplicate class com.googlecode.leptonica.android.AdaptiveMap found in modules tesseract4android-4.1.0-runtime.jar (cz.adaptech.tesseract4android:tesseract4android:4.1.0) and tesseract4android-openmp-4.1.0-runtime.jar (cz.adaptech.tesseract4android:tesseract4android-openmp:4.1.0)

**Comment by Robyer** [comment]
@WeiHungHuang Thanks for report. I released new version 4.1.1 which should be available correctly on JitPack. Old 4.0.0 also works.

**Comment by WeiHungHuang** [comment]
Thanks.

**Comment by DoozyDoz** [comment]
Hello guys,
I am still getting this duplicate error at build and am using 4.1.1

**Comment by Robyer** [comment]
@DoozyDoz Your log/error message says you are using 4.1.0, not 4.1.1.

**Comment by DoozyDoz** [comment]
@Robyer Thanks, it has no built successfully
